# RFP: Maze Solvers

## Project Overview
You are invited to submit a proposal that answers the following question:

### What path will your elf take?

*Please submit your proposal by **2/11/25 at 11:59 PM**.*

## Required Proposal Components

### 1. Data Description
In the code cell below, use [Gymnasium](https://gymnasium.farama.org/) to set up a [Frozen Lake maze](https://gymnasium.farama.org/environments/toy_text/frozen_lake/) for your project. When you are done with the set up, describe the reward system you plan on using.

*Note, a level 5 maze is at least 10 x 10 cells large and contains at least five lake cells.*

In [1]:
!pip install gymnasium
import gymnasium as gym

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import pandas as pd

In [3]:
import random

In [4]:
from tqdm.notebook import trange

In [5]:
pip install "gymnasium[toy-text]

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [6]:
# Make maze
maze=["SFFFHFFHFH", "FHFHFFFFFH", "FFFHHHFFFF", "HFFFGFFHFF", "HHFFFFHHFF",
      "FFFHFFHFFF", "FFHFHFHFFF", "HHHHFFFFFF", "FHFHFHFHFF", "HFFFFFFFFG"]
env = gym.make('FrozenLake-v1', desc=maze, render_mode='human')
initial_state = env.reset()
env.render()

# Take a step (0: LEFT, 1: DOWN, 2: RIGHT, 3: UP)
action = 2
new_state, reward, terminated, truncated, info = env.step(action)

env.render()

In [1]:
env.close()

NameError: name 'env' is not defined

#### Describe your reward system here.
+10 for gift, -1 for space, -5 for lake

### 2. Training Your Model
In the cell seen below, write the code you need to train a Q-Learning model. Display your final Q-table once you are done training your model.

*Note, level 5 work uses only the standard Python library and Pandas to train your Q-Learning model. A level 4 uses external libraries like Baseline3.*

In [8]:
# learning rate - 0.5, discount - 0.5
# Bellman Equation: (1-alpha)q(s, a) + alpha(R + gamma(max(q(s`, a`))))
# Q Table Diagram
#    Up  Down  Left  Right
# 0
# 1
# 2
# 3
# 4
# 5

q = {
    "Up": [0,0,0,0,0,0],
    "Down": [0,0,0,0,0,0],
    "Left": [0,0,0,0,0,0],
    "Right": [0,0,0,0,0,0]
}
df = pd.DataFrame(q)
df.head()

Up  Down  Left  Right
0   0     0     0      0
1   0     0     0      0
2   0     0     0      0
3   0     0     0      0
4   0     0     0      0

In [9]:
import numpy as np

# Define the environment
n_states = 100  # Number of states in the grid world
n_actions = 4  # Number of possible actions (up, down, left, right)
goal_state = 100  # Goal state

# Initialize Q-table with zeros
Q_table = np.zeros((n_states, n_actions))

In [10]:
# Define parameters
learning_rate = 0.8
discount_factor = 0.95
exploration_prob = 0.2
epochs = 1000

In [11]:
# Q-learning algorithm
'''
for epoch in range(epochs):
    current_state = np.random.randint(0, n_states)  # Start from a random state

    while current_state != goal_state:
        # Choose action with epsilon-greedy strategy
        if np.random.rand() < exploration_prob:
            action = np.random.randint(0, n_actions)  # Explore
        else:
            action = np.argmax(Q_table[current_state])  # Exploit

        # Simulate the environment (move to the next state)
        # For simplicity, move to the next state
        next_state = (current_state + 1) % n_states

        # Define a simple reward function (1 if the goal state is reached, 0 otherwise)
        reward = 1 if next_state == goal_state else 0

        # Update Q-value using the Q-learning update rule
        Q_table[current_state, action] += learning_rate * \
            (reward + discount_factor *
             np.max(Q_table[next_state]) - Q_table[current_state, action])

        current_state = next_state  # Move to the next state
        '''

'\nfor epoch in range(epochs):\n    current_state = np.random.randint(0, n_states)  # Start from a random state\n\n    while current_state != goal_state:\n        # Choose action with epsilon-greedy strategy\n        if np.random.rand() < exploration_prob:\n            action = np.random.randint(0, n_actions)  # Explore\n        else:\n            action = np.argmax(Q_table[current_state])  # Exploit\n\n        # Simulate the environment (move to the next state)\n        # For simplicity, move to the next state\n        next_state = (current_state + 1) % n_states\n\n        # Define a simple reward function (1 if the goal state is reached, 0 otherwise)\n        reward = 1 if next_state == goal_state else 0\n\n        # Update Q-value using the Q-learning update rule\n        Q_table[current_state, action] += learning_rate *             (reward + discount_factor *\n             np.max(Q_table[next_state]) - Q_table[current_state, action])\n\n        current_state = next_state  # Move to

In [12]:
# After training, the Q-table represents the learned Q-values
print("Learned Q-table:")
print(Q_table)

Learned Q-table:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 

In [13]:
def epsilon_greedy_policy(Qtable, state, epsilon):
  random_int = random.uniform(0,1)
  if random_int > epsilon:
    action = np.argmax(Qtable[state])
  else:
    action = env.action_space.sample()
  return action

In [14]:
def greedy_policy(Qtable, state):
  action = np.argmax(Qtable[state])
  return action

In [15]:
# Training parameters
n_training_episodes = 10000
learning_rate = 0.7        

# Evaluation parameters
n_eval_episodes = 100      

# Environment parameters
env_id = "FrozenLake-v1"   
max_steps = 99             
gamma = 0.95               
eval_seed = []             

# Exploration parameters
max_epsilon = 1.0           
min_epsilon = 0.05           
decay_rate = 0.0005           

In [16]:
'''def train(n_training_episodes, min_epsilon, max_epsilon, decay_rate, env, max_steps, Qtable):
  for episode in trange(n_training_episodes):
 
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    # Reset the environment
    state = env.reset()
    step = 0
    done = False

    # repeat
    for step in range(max_steps):
   
      action = epsilon_greedy_policy(Qtable, state, epsilon)

   
      #new_state, reward, done, info = env.step(action)
      new_state, reward, done, _ = env.step(action)  # Ignore 'info' if not needed


   
      Qtable[state][action] = Qtable[state][action] + learning_rate * (reward + gamma * np.max(Qtable[new_state]) - Qtable[state][action])

      # If done, finish the episode
      if done:
        break
     
      # Our state is the new state
      state = new_state
  return Qtable '''

"def train(n_training_episodes, min_epsilon, max_epsilon, decay_rate, env, max_steps, Qtable):\n  for episode in trange(n_training_episodes):\n \n    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)\n    # Reset the environment\n    state = env.reset()\n    step = 0\n    done = False\n\n    # repeat\n    for step in range(max_steps):\n   \n      action = epsilon_greedy_policy(Qtable, state, epsilon)\n\n   \n      #new_state, reward, done, info = env.step(action)\n      new_state, reward, done, _ = env.step(action)  # Ignore 'info' if not needed\n\n\n   \n      Qtable[state][action] = Qtable[state][action] + learning_rate * (reward + gamma * np.max(Qtable[new_state]) - Qtable[state][action])\n\n      # If done, finish the episode\n      if done:\n        break\n     \n      # Our state is the new state\n      state = new_state\n  return Qtable "

In [19]:
maze=["SFFFHFFHFH", "FHFHFFFFFH", "FFFHHHFFFF", "HFFFGFFHFF", "HHFFFFHHFF",
      "FFFHFFHFFF", "FFHFHFHFFF", "HHHHFFFFFF", "FHFHFHFHFF", "HFFFFFFFFG"]
env = gym.make('FrozenLake-v1', desc=maze, render_mode='human')
initial_state = env.reset()


In [20]:
def train(n_training_episodes, min_epsilon, max_epsilon, decay_rate, env, max_steps, Qtable, learning_rate, gamma):
    for episode in trange(n_training_episodes):
        
        # Calculate epsilon for the epsilon-greedy policy
        epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
        
        # Reset the environment
        state, _ = env.reset()  # Reset and get the initial state
        done = False

        # Repeat for each step in the episode
        for step in range(max_steps):
            
            # Choose action using epsilon-greedy policy
            action = epsilon_greedy_policy(Qtable, state, epsilon)

            # Take the action and observe the result
            observation, reward, done, _ = env.step(action)  # Proper unpacking for the step method
           
            # Update Q-table using the Q-learning formula
            Qtable[state][action] = Qtable[state][action] + learning_rate * (reward + gamma * np.max(Qtable[observation]) - Qtable[state][action])
            
            # If done, finish the episode
            if done:
                break
            
            # Our state is the new state
            state = observation
            
    return Qtable




In [21]:
Qtable_frozenlake = train(n_training_episodes, min_epsilon, max_epsilon, decay_rate, env, max_steps, Q_table, 0.5, 0.5)

  0%|          | 0/10000 [00:00<?, ?it/s]

ValueError: too many values to unpack (expected 4)

In [ ]:
# Train model here.
# Don't forget to display your final Q table!

### 3. Testing Your Model
In the cell seen below, write the code you need to test your Q-Learning model for **1000 episodes**. It is important to test your model for 1000 episodes so that we are all able to compare our results.

*Note, level 5 testing uses both a success rate and an average steps taken metric to evaluate your model. Level 4 uses one or the other.*

In [ ]:
# Test model here.

### 4. Final Answer
In the first cell below, describe the path your elf takes to get to the gift. *Note, a level 5 answer includes a gif of the path your elf takes in order to reach the gift.*

In the second cell seen below, describe how well your Q-Learning model performed. Make sure that you explicitly name the **learning rate**, **the discount factor**, and the **reward system** that you used when training your final model. *Note, a level 5 description describes the model's performance using two types of quantitative evidence.*

![example image](https://gymnasium.farama.org/_images/frozen_lake.gif)

#### Describe the path your elf takes here.

#### Describe how well your Q-Learning model performed here.